# Generated by Django 4.2.4 on 2023-09-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionMascotas', '0002_pet_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
