# Generated by Django 4.2.5 on 2023-09-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionMascotas', '0003_pet_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='state',
        ),
        migrations.AddField(
            model_name='pet',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdopcionMascotas.state', verbose_name='Estado'),
        ),
    ]
