# Generated by Django 4.2.4 on 2023-09-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionMascotas', '0004_remove_pet_state_pet_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='StatePet',
        ),
        migrations.AlterModelOptions(
            name='statepet',
            options={'ordering': ['id'], 'verbose_name': 'Estado Mascota', 'verbose_name_plural': 'Estados Mascotas'},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='State',
            new_name='StatePet',
        ),
        migrations.AlterModelTable(
            name='statepet',
            table='Estado Mascota',
        ),
    ]
