# Generated by Django 4.2.4 on 2023-09-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdopcionMascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=7, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Sub Total')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('pets', models.ManyToManyField(to='AdopcionMascotas.pet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
