# Generated by Django 5.0.3 on 2024-03-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CajaMascotas', '0002_alter_adoptbox_box_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado Caja',
                'verbose_name_plural': 'Estados Cajas',
                'db_table': 'Estado Caja',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='adoptbox',
            name='StateBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CajaMascotas.statebox', verbose_name='Estado'),
        ),
    ]
