# Generated by Django 5.0.3 on 2024-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CajaMascotas', '0003_statebox_adoptbox_statebox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptbox',
            options={'ordering': ['id'], 'verbose_name': 'Caja Adopcion', 'verbose_name_plural': 'Cajas Adopciones'},
        ),
        migrations.AlterModelTable(
            name='adoptbox',
            table='caja_adopcion',
        ),
        migrations.AlterModelTable(
            name='statebox',
            table='estado_caja',
        ),
    ]
