# Generated by Django 5.0.3 on 2024-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CajaMascotas', '0004_alter_adoptbox_options_alter_adoptbox_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adoptbox',
            table='Caja Adopcion',
        ),
        migrations.AlterModelTable(
            name='statebox',
            table='Estado Caja',
        ),
    ]
