# Generated by Django 5.0.2 on 2024-04-04 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_adoption',
            name='time',
            field=models.TextField(default=1, verbose_name='¿Sus responsabilidades le permiten tener tiempo de calidad con la mascota?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='capacityMoney',
            field=models.TextField(verbose_name='¿Considera que puede mantener una mascota con su salario actual?'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='disposition',
            field=models.TextField(verbose_name='¿Esta dispuesto a Firmar un contrato de adopcion?'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='documentBack',
            field=models.ImageField(max_length=200, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])], verbose_name='Documento Cara Trasera'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='documentFront',
            field=models.ImageField(max_length=200, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])], verbose_name='Documento Cara Delantera'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='visits',
            field=models.TextField(verbose_name='¿Esta dispuesto a recibir visitas mensuales para validar que la mascota se encuentre bien ?'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='work',
            field=models.TextField(verbose_name='¿Describa su trabajo?'),
        ),
    ]
