# Generated by Django 5.0.2 on 2024-04-04 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_adopcion', '0002_form_adoption_time_alter_form_adoption_capacitymoney_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_adoption',
            name='documentBack',
            field=models.ImageField(max_length=200, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg'])], verbose_name='Documento Cara Trasera'),
        ),
        migrations.AlterField(
            model_name='form_adoption',
            name='documentFront',
            field=models.ImageField(max_length=200, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg'])], verbose_name='Documento Cara Delantera'),
        ),
    ]
