# Generated by Django 5.0.2 on 2024-04-01 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0002_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Carrito')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Sub Total')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_boxes', to='Productos.product')),
                ('product_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_in_boxes', to='CarroProductos.productbox')),
            ],
        ),
        migrations.AddField(
            model_name='productbox',
            name='products',
            field=models.ManyToManyField(through='CarroProductos.ProductInBox', to='Productos.product', verbose_name='Productos'),
        ),
    ]
