
# Generated by Django 5.0.2 on 2024-04-04 14:59

# Generated by Django 5.0.1 on 2024-04-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarroProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbox',
            options={'ordering': ['id'], 'verbose_name': 'Carro Productos', 'verbose_name_plural': 'Carro Productos'},
        ),
    ]
