# Generated by Django 4.2.4 on 2023-09-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CajaMascotas', '0002_alter_adoptbox_box_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(orders.models.OrderStatus['CREADO'], 'CREADO'), (orders.models.OrderStatus['SOLICITADO'], 'SOLICITADO'), (orders.models.OrderStatus['ADOPTADO'], 'ADOPTADO'), (orders.models.OrderStatus['COMPLETADO'], 'COMPLETADO'), (orders.models.OrderStatus['CANCELADO'], 'CANCELADO')], default=orders.models.OrderStatus['CREADO'], max_length=50)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5000, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CajaMascotas.adoptbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
