# Generated by Django 5.0.2 on 2024-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad_vendida',
            field=models.IntegerField(default=0, verbose_name='Cantidad Vendida'),
        ),
    ]
